### ISSUE TITLE
Deploy Kastau Docs menggunakan MkDocs

### ISSUE THREAD

**Issue by danielcristho** [antroy-tech/kastau-terjemahan#14]
- [ ] Create Github Page.
- [ ]  Create Github Action for MkDocs deployment.
- [ ] Buat isi dokumentasi lebih baik.

**Comment by antheiz** [comment]
> * [ ]  Create Github Page.
> 
>     * [ ]   Create Github Action for MkDocs deployment.
> 
>     * [ ]  Buat isi dokumentasi lebih baik.

Sorry, i think this issue is similar to the one found here:
https://github.com/antroy-tech/kastau-terjemahan/issues/7

If you don't mind, I can close this issue, and you can focus on the issue I mentioned earlier.
